/**
 * Simulator Event Types
 *
 * Defines the standardized event types used in the simulator event stream.
 * These match the backend event types to ensure type safety and eliminate magic strings.
 */

/**
 * Simulator-specific events (timers, etc)
 */
export enum SimulatorEventType {
  TIMER_SCHEDULED = "simulator.timer_scheduled",
  TIMER_FIRED = "simulator.timer_fired",
  TIMER_CANCELLED = "simulator.timer_cancelled",
}

/**
 * System events generated by the engine
 * Updated to match new naming conventions (engine.*, session.*, timer.*, etc.)
 */
export enum SystemEventType {
  MESSAGE = "engine.message",
  TRANSITION = "engine.transition",
  TIMEOUT = "timer.expired",
  ERROR = "engine.error",
  TAG = "session.tags",
  VARIABLE = "session.variables",
  TELEPORT = "journey.teleport",
  MINDSTATE = "mindstate.updated",
  CRM = "journey.crm",
  FOLLOWUP = "timer.followup",
}

// Note: User events (user.message, user.click) use EventTypes from @journey/schemas
// No local enum needed since they're not used in special handlers
