/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  ⚠️  WARNING: AUTO-GENERATED FILE - DO NOT EDIT MANUALLY! ⚠️              ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║                                                                          ║
 * ║  This file is generated by: packages/llm/src/config/genesis-models.js    ║
 * ║                                                                          ║
 * ║  To update model pricing or add new models:                              ║
 * ║  1. Edit genesis-models.js (the SOURCE file)                             ║
 * ║  2. Run: node packages/llm/src/config/genesis-models.js                  ║
 * ║                                                                          ║
 * ║  ANY CHANGES TO THIS FILE WILL BE OVERWRITTEN!                           ║
 * ║                                                                          ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */

import type { ModelMetadata } from "./model-registry";

export const ESSENTIAL_MODELS: ModelMetadata[] = [
  {
    "id": "llama-3.1-8b-instant",
    "displayName": "Llama 3.1 8B Instant",
    "provider": "groq",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.05,
      "output": 0.08
    },
    "contextWindow": 131072,
    "outputLimit": 131072
  },
  {
    "id": "moonshotai/kimi-k2-instruct-0905",
    "displayName": "Kimi K2 Instruct 0905",
    "provider": "groq",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 1,
      "output": 3
    },
    "contextWindow": 262144,
    "outputLimit": 16384
  },
  {
    "id": "openai/gpt-oss-20b",
    "displayName": "GPT OSS 20B",
    "provider": "groq",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.075,
      "output": 0.3
    },
    "contextWindow": 131072,
    "outputLimit": 65536
  },
  {
    "id": "openai/gpt-oss-120b",
    "displayName": "GPT OSS 120B",
    "provider": "groq",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.15,
      "output": 0.6
    },
    "contextWindow": 131072,
    "outputLimit": 65536
  },
  {
    "id": "qwen/qwen3-32b",
    "displayName": "Qwen3 32B",
    "provider": "groq",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.29,
      "output": 0.59
    },
    "contextWindow": 131072,
    "outputLimit": 16384
  },
  {
    "id": "meta-llama/llama-4-maverick-17b-128e-instruct",
    "displayName": "Llama 4 Maverick 17B",
    "provider": "groq",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.2,
      "output": 0.6
    },
    "contextWindow": 131072,
    "outputLimit": 8192
  },
  {
    "id": "meta-llama/llama-guard-4-12b",
    "displayName": "Llama Guard 4 12B",
    "provider": "groq",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0.2,
      "output": 0.2
    },
    "contextWindow": 131072,
    "outputLimit": 1024
  },
  {
    "id": "gemini-3-flash-preview",
    "displayName": "Gemini 3 Flash Preview",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.5,
      "output": 3,
      "cacheRead": 0.05
    },
    "contextWindow": 1048576,
    "outputLimit": 65536
  },
  {
    "id": "gemini-2.5-flash-image",
    "displayName": "Gemini 2.5 Flash Image",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": false
    },
    "pricing": {
      "input": 0.3,
      "output": 30,
      "cacheRead": 0.075
    },
    "contextWindow": 32768,
    "outputLimit": 32768
  },
  {
    "id": "gemini-flash-lite-latest",
    "displayName": "Gemini Flash-Lite Latest",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.1,
      "output": 0.4,
      "cacheRead": 0.025
    },
    "contextWindow": 1048576,
    "outputLimit": 65536
  },
  {
    "id": "gemini-3-pro-preview",
    "displayName": "Gemini 3 Pro Preview",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 2,
      "output": 12,
      "cacheRead": 0.2
    },
    "contextWindow": 1000000,
    "outputLimit": 64000
  },
  {
    "id": "gemini-2.5-flash",
    "displayName": "Gemini 2.5 Flash",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.3,
      "output": 2.5,
      "cacheRead": 0.075
    },
    "contextWindow": 1048576,
    "outputLimit": 65536
  },
  {
    "id": "gemini-flash-latest",
    "displayName": "Gemini Flash Latest",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.3,
      "output": 2.5,
      "cacheRead": 0.075
    },
    "contextWindow": 1048576,
    "outputLimit": 65536
  },
  {
    "id": "gemini-2.5-flash-lite",
    "displayName": "Gemini 2.5 Flash Lite",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.1,
      "output": 0.4,
      "cacheRead": 0.025
    },
    "contextWindow": 1048576,
    "outputLimit": 65536
  },
  {
    "id": "gemini-live-2.5-flash",
    "displayName": "Gemini Live 2.5 Flash",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.5,
      "output": 2
    },
    "contextWindow": 128000,
    "outputLimit": 8000
  },
  {
    "id": "gemini-2.5-flash-image-preview",
    "displayName": "Gemini 2.5 Flash Image (Preview)",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": false
    },
    "pricing": {
      "input": 0.3,
      "output": 30,
      "cacheRead": 0.075
    },
    "contextWindow": 32768,
    "outputLimit": 32768
  },
  {
    "id": "gemini-2.5-flash-preview-09-2025",
    "displayName": "Gemini 2.5 Flash Preview 09-25",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.3,
      "output": 2.5,
      "cacheRead": 0.075
    },
    "contextWindow": 1048576,
    "outputLimit": 65536
  },
  {
    "id": "gemini-2.5-pro",
    "displayName": "Gemini 2.5 Pro",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 1.25,
      "output": 10,
      "cacheRead": 0.31
    },
    "contextWindow": 1048576,
    "outputLimit": 65536
  },
  {
    "id": "gemini-2.5-flash-lite-preview-09-2025",
    "displayName": "Gemini 2.5 Flash Lite Preview 09-25",
    "provider": "google-genai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.1,
      "output": 0.4,
      "cacheRead": 0.025
    },
    "contextWindow": 1048576,
    "outputLimit": 65536
  },
  {
    "id": "gpt-4.1-mini",
    "displayName": "GPT-4.1 mini",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": false,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.4,
      "output": 1.6,
      "cacheRead": 0.1
    },
    "contextWindow": 1047576,
    "outputLimit": 32768
  },
  {
    "id": "gpt-5.2-pro",
    "displayName": "GPT-5.2 Pro",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 21,
      "output": 168
    },
    "contextWindow": 400000,
    "outputLimit": 128000
  },
  {
    "id": "gpt-5.2-chat-latest",
    "displayName": "GPT-5.2 Chat",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 1.75,
      "output": 14,
      "cacheRead": 0.175
    },
    "contextWindow": 128000,
    "outputLimit": 16384
  },
  {
    "id": "gpt-5.1",
    "displayName": "GPT-5.1",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 1.25,
      "output": 10,
      "cacheRead": 0.13
    },
    "contextWindow": 400000,
    "outputLimit": 128000
  },
  {
    "id": "gpt-5-nano",
    "displayName": "GPT-5 Nano",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.05,
      "output": 0.4,
      "cacheRead": 0.01
    },
    "contextWindow": 400000,
    "outputLimit": 128000
  },
  {
    "id": "gpt-5-mini",
    "displayName": "GPT-5 Mini",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.25,
      "output": 2,
      "cacheRead": 0.03
    },
    "contextWindow": 400000,
    "outputLimit": 128000
  },
  {
    "id": "gpt-5-chat-latest",
    "displayName": "GPT-5 Chat (latest)",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": false
    },
    "pricing": {
      "input": 1.25,
      "output": 10
    },
    "contextWindow": 400000,
    "outputLimit": 128000
  },
  {
    "id": "gpt-4o-mini",
    "displayName": "GPT-4o mini",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": false,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.15,
      "output": 0.6,
      "cacheRead": 0.08
    },
    "contextWindow": 128000,
    "outputLimit": 16384
  },
  {
    "id": "gpt-5",
    "displayName": "GPT-5",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 1.25,
      "output": 10,
      "cacheRead": 0.13
    },
    "contextWindow": 400000,
    "outputLimit": 128000
  },
  {
    "id": "gpt-5-pro",
    "displayName": "GPT-5 Pro",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 15,
      "output": 120
    },
    "contextWindow": 400000,
    "outputLimit": 272000
  },
  {
    "id": "gpt-5.2",
    "displayName": "GPT-5.2",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 1.75,
      "output": 14,
      "cacheRead": 0.175
    },
    "contextWindow": 400000,
    "outputLimit": 128000
  },
  {
    "id": "gpt-5.1-chat-latest",
    "displayName": "GPT-5.1 Chat",
    "provider": "openai",
    "category": "llm",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 1.25,
      "output": 10,
      "cacheRead": 0.125
    },
    "contextWindow": 128000,
    "outputLimit": 16384
  },
  {
    "id": "claude-opus-4-1",
    "displayName": "Claude Opus 4.1 (latest)",
    "provider": "anthropic",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 15,
      "output": 75,
      "cacheRead": 1.5,
      "cacheWrite": 18.75
    },
    "contextWindow": 200000,
    "outputLimit": 32000
  },
  {
    "id": "claude-haiku-4-5",
    "displayName": "Claude Haiku 4.5 (latest)",
    "provider": "anthropic",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 1,
      "output": 5,
      "cacheRead": 0.1,
      "cacheWrite": 1.25
    },
    "contextWindow": 200000,
    "outputLimit": 64000
  },
  {
    "id": "claude-opus-4-5",
    "displayName": "Claude Opus 4.5 (latest)",
    "provider": "anthropic",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 5,
      "output": 25,
      "cacheRead": 0.5,
      "cacheWrite": 6.25
    },
    "contextWindow": 200000,
    "outputLimit": 64000
  },
  {
    "id": "claude-opus-4-5-20251101",
    "displayName": "Claude Opus 4.5",
    "provider": "anthropic",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 5,
      "output": 25,
      "cacheRead": 0.5,
      "cacheWrite": 6.25
    },
    "contextWindow": 200000,
    "outputLimit": 64000
  },
  {
    "id": "claude-sonnet-4-5",
    "displayName": "Claude Sonnet 4.5 (latest)",
    "provider": "anthropic",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 3,
      "output": 15,
      "cacheRead": 0.3,
      "cacheWrite": 3.75
    },
    "contextWindow": 200000,
    "outputLimit": 64000
  },
  {
    "id": "claude-sonnet-4-5-20250929",
    "displayName": "Claude Sonnet 4.5",
    "provider": "anthropic",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 3,
      "output": 15,
      "cacheRead": 0.3,
      "cacheWrite": 3.75
    },
    "contextWindow": 200000,
    "outputLimit": 64000
  },
  {
    "id": "claude-opus-4-1-20250805",
    "displayName": "Claude Opus 4.1",
    "provider": "anthropic",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 15,
      "output": 75,
      "cacheRead": 1.5,
      "cacheWrite": 18.75
    },
    "contextWindow": 200000,
    "outputLimit": 32000
  },
  {
    "id": "claude-haiku-4-5-20251001",
    "displayName": "Claude Haiku 4.5",
    "provider": "anthropic",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": true,
      "toolCalling": true
    },
    "pricing": {
      "input": 1,
      "output": 5,
      "cacheRead": 0.1,
      "cacheWrite": 1.25
    },
    "contextWindow": 200000,
    "outputLimit": 64000
  },
  {
    "id": "tts-1",
    "displayName": "TTS-1 (Standard)",
    "provider": "openai",
    "category": "audio",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0,
      "output": 0,
      "perCharacter": 0.000015
    },
    "contextWindow": 0,
    "outputLimit": 0
  },
  {
    "id": "tts-1-hd",
    "displayName": "TTS-1 HD (High Definition)",
    "provider": "openai",
    "category": "audio",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0,
      "output": 0,
      "perCharacter": 0.00003
    },
    "contextWindow": 0,
    "outputLimit": 0
  },
  {
    "id": "gpt-4o-mini-tts",
    "displayName": "GPT-4o Mini TTS",
    "provider": "openai",
    "category": "audio",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0,
      "output": 0,
      "perCharacter": 0.000015
    },
    "contextWindow": 0,
    "outputLimit": 0
  },
  {
    "id": "gpt-4o-transcribe",
    "displayName": "GPT-4o Transcribe",
    "provider": "openai",
    "category": "audio",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0,
      "output": 0,
      "perSecond": 0.0001
    },
    "contextWindow": 0,
    "outputLimit": 0
  },
  {
    "id": "eleven_flash_v2_5",
    "displayName": "ElevenLabs Flash v2.5",
    "provider": "elevenlabs",
    "category": "audio",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0,
      "output": 0,
      "perCharacter": 0.000167
    },
    "contextWindow": 0,
    "outputLimit": 0,
    "audio": {
      "label": "Flash v2.5 (Streaming)",
      "description": "Ultra-low latency streaming (~75ms)",
      "languages": 29,
      "experimental": false,
      "type": "tts"
    }
  },
  {
    "id": "eleven_multilingual_v2",
    "displayName": "ElevenLabs Multilingual v2",
    "provider": "elevenlabs",
    "category": "audio",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0,
      "output": 0,
      "perCharacter": 0.000167
    },
    "contextWindow": 0,
    "outputLimit": 0,
    "audio": {
      "label": "Multilingual v2 (Stable)",
      "description": "Most lifelike model with rich emotional expression",
      "languages": 29,
      "experimental": false,
      "type": "tts"
    }
  },
  {
    "id": "eleven_v3",
    "displayName": "ElevenLabs v3",
    "provider": "elevenlabs",
    "category": "audio",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0,
      "output": 0,
      "perCharacter": 0.000167
    },
    "contextWindow": 0,
    "outputLimit": 0,
    "audio": {
      "label": "v3 (Experimental)",
      "description": "Human-like and expressive speech generation",
      "languages": 70,
      "experimental": true,
      "type": "tts"
    }
  },
  {
    "id": "eleven_turbo_v2_5",
    "displayName": "ElevenLabs Turbo v2.5",
    "provider": "elevenlabs",
    "category": "audio",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0,
      "output": 0,
      "perCharacter": 0.000167
    },
    "contextWindow": 0,
    "outputLimit": 0,
    "audio": {
      "label": "Turbo v2.5",
      "description": "Fast generation with good quality",
      "languages": 29,
      "experimental": false,
      "type": "tts"
    }
  },
  {
    "id": "scribe_v1",
    "displayName": "ElevenLabs Scribe v1",
    "provider": "elevenlabs",
    "category": "audio",
    "supportsTemperature": false,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": false
    },
    "pricing": {
      "input": 0,
      "output": 0,
      "perSecond": 0.000167
    },
    "contextWindow": 0,
    "outputLimit": 0,
    "audio": {
      "label": "Scribe v1",
      "description": "Speech recognition with 99 language support",
      "languages": 99,
      "experimental": false,
      "type": "stt"
    }
  },
  {
    "id": "llama3.1-8b",
    "displayName": "Llama 3.1 8B (Cerebras)",
    "provider": "cerebras",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.1,
      "output": 0.1
    },
    "contextWindow": 131072,
    "outputLimit": 8192
  },
  {
    "id": "llama-3.3-70b",
    "displayName": "Llama 3.3 70B (Cerebras)",
    "provider": "cerebras",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": false,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.85,
      "output": 1.2
    },
    "contextWindow": 131072,
    "outputLimit": 8192
  },
  {
    "id": "gpt-oss-120b",
    "displayName": "GPT OSS 120B (Cerebras)",
    "provider": "cerebras",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.35,
      "output": 0.75
    },
    "contextWindow": 131072,
    "outputLimit": 65536
  },
  {
    "id": "qwen-3-32b",
    "displayName": "Qwen 3 32B (Cerebras)",
    "provider": "cerebras",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.4,
      "output": 0.8
    },
    "contextWindow": 131072,
    "outputLimit": 8192
  },
  {
    "id": "zai-glm-4.7",
    "displayName": "Z.ai GLM 4.7 (Cerebras)",
    "provider": "cerebras",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 0.5,
      "output": 1
    },
    "contextWindow": 131072,
    "outputLimit": 8192
  },
  {
    "id": "qwen-3-235b-a22b-instruct-2507",
    "displayName": "Qwen 3 235B Instruct (Cerebras)",
    "provider": "cerebras",
    "category": "llm",
    "supportsTemperature": true,
    "capabilities": {
      "reasoning": true,
      "vision": false,
      "toolCalling": true
    },
    "pricing": {
      "input": 1,
      "output": 2
    },
    "contextWindow": 131072,
    "outputLimit": 8192
  }
];

// =============================================================================
// ElevenLabs Model Configurations (for UI model selection)
// =============================================================================

/**
 * ElevenLabs TTS model configuration entry
 */
export interface ElevenLabsModelConfig {
  id: string;
  label: string;
  description: string;
  languages: number;
  experimental: boolean;
}

/**
 * ElevenLabs TTS models for UI selection
 * Keys: multilingual_v2, v3, flash_v2_5, turbo_v2_5
 */
export const ELEVENLABS_TTS_MODELS = {
  "flash_v2_5": {
    "id": "eleven_flash_v2_5",
    "label": "Flash v2.5 (Streaming)",
    "description": "Ultra-low latency streaming (~75ms)",
    "languages": 29,
    "experimental": false
  },
  "multilingual_v2": {
    "id": "eleven_multilingual_v2",
    "label": "Multilingual v2 (Stable)",
    "description": "Most lifelike model with rich emotional expression",
    "languages": 29,
    "experimental": false
  },
  "v3": {
    "id": "eleven_v3",
    "label": "v3 (Experimental)",
    "description": "Human-like and expressive speech generation",
    "languages": 70,
    "experimental": true
  },
  "turbo_v2_5": {
    "id": "eleven_turbo_v2_5",
    "label": "Turbo v2.5",
    "description": "Fast generation with good quality",
    "languages": 29,
    "experimental": false
  }
} as const;

/**
 * ElevenLabs STT models for UI selection
 */
export const ELEVENLABS_STT_MODELS = {
  "scribe_v1": {
    "id": "scribe_v1",
    "label": "Scribe v1",
    "description": "Speech recognition with 99 language support",
    "languages": 99,
    "experimental": false
  }
} as const;

/**
 * Union type of all ElevenLabs TTS model IDs
 */
export type ElevenLabsTtsModelId = (typeof ELEVENLABS_TTS_MODELS)[keyof typeof ELEVENLABS_TTS_MODELS]["id"];

/**
 * Union type of all ElevenLabs STT model IDs
 */
export type ElevenLabsSttModelId = (typeof ELEVENLABS_STT_MODELS)[keyof typeof ELEVENLABS_STT_MODELS]["id"];

// =============================================================================
// Model Lookup Utilities
// =============================================================================

/**
 * Get all essential model IDs as a string array
 */
export function getEssentialModelIds(): string[] {
  return ESSENTIAL_MODELS.map((m) => m.id);
}

/**
 * Look up model metadata by ID
 * Returns undefined if model is not found in the essential models registry
 */
export function getModelMetadata(modelId: string): ModelMetadata | undefined {
  return ESSENTIAL_MODELS.find((m) => m.id === modelId);
}

/**
 * Union type of all essential model IDs
 * Derives from ESSENTIAL_MODELS array for type safety
 */
export type EssentialModelId = (typeof ESSENTIAL_MODELS)[number]["id"];
