/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as R503RouteImport } from './routes/503'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as R401RouteImport } from './routes/401'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardUsersTestRouteImport } from './routes/_dashboard.users-test'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard.users'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardPromptsRouteImport } from './routes/_dashboard.prompts'
import { Route as DashboardMindstateRouteImport } from './routes/_dashboard.mindstate'
import { Route as DashboardJourneysRouteImport } from './routes/_dashboard.journeys'
import { Route as DashboardCrmRouteImport } from './routes/_dashboard.crm'
import { Route as DashboardAgentsRouteImport } from './routes/_dashboard.agents'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard.settings.index'
import { Route as DashboardPromptsIndexRouteImport } from './routes/_dashboard.prompts.index'
import { Route as DashboardMindstateIndexRouteImport } from './routes/_dashboard.mindstate.index'
import { Route as DashboardJourneysIndexRouteImport } from './routes/_dashboard.journeys.index'
import { Route as DashboardCrmIndexRouteImport } from './routes/_dashboard.crm.index'
import { Route as DashboardAgentsIndexRouteImport } from './routes/_dashboard.agents.index'
import { Route as DashboardSettingsVariablesRouteImport } from './routes/_dashboard.settings.variables'
import { Route as DashboardSettingsTagsRouteImport } from './routes/_dashboard.settings.tags'
import { Route as DashboardSettingsProfileRouteImport } from './routes/_dashboard.settings.profile'
import { Route as DashboardSettingsOrganisationRouteImport } from './routes/_dashboard.settings.organisation'
import { Route as DashboardSettingsJourneyPipelinesRouteImport } from './routes/_dashboard.settings.journey-pipelines'
import { Route as DashboardSettingsJourneyMindstateRouteImport } from './routes/_dashboard.settings.journey-mindstate'
import { Route as DashboardSettingsImportExportRouteImport } from './routes/_dashboard.settings.import-export'
import { Route as DashboardSettingsChannelsRouteImport } from './routes/_dashboard.settings.channels'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/_dashboard.settings.appearance'
import { Route as DashboardPromptsNewRouteImport } from './routes/_dashboard.prompts.new'
import { Route as DashboardPromptsPromptNameRouteImport } from './routes/_dashboard.prompts.$promptName'
import { Route as DashboardMindstateDefinitionKeyRouteImport } from './routes/_dashboard.mindstate.$definitionKey'
import { Route as DashboardJourneysJourneySlugRouteImport } from './routes/_dashboard.journeys.$journeySlug'
import { Route as DashboardDevelopersEventsRouteImport } from './routes/_dashboard.developers.events'
import { Route as DashboardAgentsAgentKeyRouteImport } from './routes/_dashboard.agents.$agentKey'
import { Route as DashboardCrmUsersUserIdRouteImport } from './routes/_dashboard.crm.users.$userId'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const R503Route = R503RouteImport.update({
  id: '/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersTestRoute = DashboardUsersTestRouteImport.update({
  id: '/users-test',
  path: '/users-test',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPromptsRoute = DashboardPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMindstateRoute = DashboardMindstateRouteImport.update({
  id: '/mindstate',
  path: '/mindstate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJourneysRoute = DashboardJourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrmRoute = DashboardCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardPromptsIndexRoute = DashboardPromptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPromptsRoute,
} as any)
const DashboardMindstateIndexRoute = DashboardMindstateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardMindstateRoute,
} as any)
const DashboardJourneysIndexRoute = DashboardJourneysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardJourneysRoute,
} as any)
const DashboardCrmIndexRoute = DashboardCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCrmRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAgentsRoute,
} as any)
const DashboardSettingsVariablesRoute =
  DashboardSettingsVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsTagsRoute = DashboardSettingsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsOrganisationRoute =
  DashboardSettingsOrganisationRouteImport.update({
    id: '/organisation',
    path: '/organisation',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsJourneyPipelinesRoute =
  DashboardSettingsJourneyPipelinesRouteImport.update({
    id: '/journey-pipelines',
    path: '/journey-pipelines',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsJourneyMindstateRoute =
  DashboardSettingsJourneyMindstateRouteImport.update({
    id: '/journey-mindstate',
    path: '/journey-mindstate',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsImportExportRoute =
  DashboardSettingsImportExportRouteImport.update({
    id: '/import-export',
    path: '/import-export',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsChannelsRoute =
  DashboardSettingsChannelsRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardPromptsNewRoute = DashboardPromptsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardPromptsRoute,
} as any)
const DashboardPromptsPromptNameRoute =
  DashboardPromptsPromptNameRouteImport.update({
    id: '/$promptName',
    path: '/$promptName',
    getParentRoute: () => DashboardPromptsRoute,
  } as any)
const DashboardMindstateDefinitionKeyRoute =
  DashboardMindstateDefinitionKeyRouteImport.update({
    id: '/$definitionKey',
    path: '/$definitionKey',
    getParentRoute: () => DashboardMindstateRoute,
  } as any)
const DashboardJourneysJourneySlugRoute =
  DashboardJourneysJourneySlugRouteImport.update({
    id: '/$journeySlug',
    path: '/$journeySlug',
    getParentRoute: () => DashboardJourneysRoute,
  } as any)
const DashboardDevelopersEventsRoute =
  DashboardDevelopersEventsRouteImport.update({
    id: '/developers/events',
    path: '/developers/events',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAgentKeyRoute = DashboardAgentsAgentKeyRouteImport.update({
  id: '/$agentKey',
  path: '/$agentKey',
  getParentRoute: () => DashboardAgentsRoute,
} as any)
const DashboardCrmUsersUserIdRoute = DashboardCrmUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardCrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/503': typeof R503Route
  '/error': typeof ErrorRoute
  '/agents': typeof DashboardAgentsRouteWithChildren
  '/crm': typeof DashboardCrmRouteWithChildren
  '/journeys': typeof DashboardJourneysRouteWithChildren
  '/mindstate': typeof DashboardMindstateRouteWithChildren
  '/prompts': typeof DashboardPromptsRouteWithChildren
  '/settings': typeof DashboardSettingsRouteWithChildren
  '/users': typeof DashboardUsersRoute
  '/users-test': typeof DashboardUsersTestRoute
  '/': typeof DashboardIndexRoute
  '/agents/$agentKey': typeof DashboardAgentsAgentKeyRoute
  '/developers/events': typeof DashboardDevelopersEventsRoute
  '/journeys/$journeySlug': typeof DashboardJourneysJourneySlugRoute
  '/mindstate/$definitionKey': typeof DashboardMindstateDefinitionKeyRoute
  '/prompts/$promptName': typeof DashboardPromptsPromptNameRoute
  '/prompts/new': typeof DashboardPromptsNewRoute
  '/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/settings/channels': typeof DashboardSettingsChannelsRoute
  '/settings/import-export': typeof DashboardSettingsImportExportRoute
  '/settings/journey-mindstate': typeof DashboardSettingsJourneyMindstateRoute
  '/settings/journey-pipelines': typeof DashboardSettingsJourneyPipelinesRoute
  '/settings/organisation': typeof DashboardSettingsOrganisationRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/settings/tags': typeof DashboardSettingsTagsRoute
  '/settings/variables': typeof DashboardSettingsVariablesRoute
  '/agents/': typeof DashboardAgentsIndexRoute
  '/crm/': typeof DashboardCrmIndexRoute
  '/journeys/': typeof DashboardJourneysIndexRoute
  '/mindstate/': typeof DashboardMindstateIndexRoute
  '/prompts/': typeof DashboardPromptsIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/crm/users/$userId': typeof DashboardCrmUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/503': typeof R503Route
  '/error': typeof ErrorRoute
  '/users': typeof DashboardUsersRoute
  '/users-test': typeof DashboardUsersTestRoute
  '/': typeof DashboardIndexRoute
  '/agents/$agentKey': typeof DashboardAgentsAgentKeyRoute
  '/developers/events': typeof DashboardDevelopersEventsRoute
  '/journeys/$journeySlug': typeof DashboardJourneysJourneySlugRoute
  '/mindstate/$definitionKey': typeof DashboardMindstateDefinitionKeyRoute
  '/prompts/$promptName': typeof DashboardPromptsPromptNameRoute
  '/prompts/new': typeof DashboardPromptsNewRoute
  '/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/settings/channels': typeof DashboardSettingsChannelsRoute
  '/settings/import-export': typeof DashboardSettingsImportExportRoute
  '/settings/journey-mindstate': typeof DashboardSettingsJourneyMindstateRoute
  '/settings/journey-pipelines': typeof DashboardSettingsJourneyPipelinesRoute
  '/settings/organisation': typeof DashboardSettingsOrganisationRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/settings/tags': typeof DashboardSettingsTagsRoute
  '/settings/variables': typeof DashboardSettingsVariablesRoute
  '/agents': typeof DashboardAgentsIndexRoute
  '/crm': typeof DashboardCrmIndexRoute
  '/journeys': typeof DashboardJourneysIndexRoute
  '/mindstate': typeof DashboardMindstateIndexRoute
  '/prompts': typeof DashboardPromptsIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/crm/users/$userId': typeof DashboardCrmUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/503': typeof R503Route
  '/_dashboard': typeof DashboardRouteWithChildren
  '/error': typeof ErrorRoute
  '/_dashboard/agents': typeof DashboardAgentsRouteWithChildren
  '/_dashboard/crm': typeof DashboardCrmRouteWithChildren
  '/_dashboard/journeys': typeof DashboardJourneysRouteWithChildren
  '/_dashboard/mindstate': typeof DashboardMindstateRouteWithChildren
  '/_dashboard/prompts': typeof DashboardPromptsRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/users-test': typeof DashboardUsersTestRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/agents/$agentKey': typeof DashboardAgentsAgentKeyRoute
  '/_dashboard/developers/events': typeof DashboardDevelopersEventsRoute
  '/_dashboard/journeys/$journeySlug': typeof DashboardJourneysJourneySlugRoute
  '/_dashboard/mindstate/$definitionKey': typeof DashboardMindstateDefinitionKeyRoute
  '/_dashboard/prompts/$promptName': typeof DashboardPromptsPromptNameRoute
  '/_dashboard/prompts/new': typeof DashboardPromptsNewRoute
  '/_dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/_dashboard/settings/channels': typeof DashboardSettingsChannelsRoute
  '/_dashboard/settings/import-export': typeof DashboardSettingsImportExportRoute
  '/_dashboard/settings/journey-mindstate': typeof DashboardSettingsJourneyMindstateRoute
  '/_dashboard/settings/journey-pipelines': typeof DashboardSettingsJourneyPipelinesRoute
  '/_dashboard/settings/organisation': typeof DashboardSettingsOrganisationRoute
  '/_dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/_dashboard/settings/tags': typeof DashboardSettingsTagsRoute
  '/_dashboard/settings/variables': typeof DashboardSettingsVariablesRoute
  '/_dashboard/agents/': typeof DashboardAgentsIndexRoute
  '/_dashboard/crm/': typeof DashboardCrmIndexRoute
  '/_dashboard/journeys/': typeof DashboardJourneysIndexRoute
  '/_dashboard/mindstate/': typeof DashboardMindstateIndexRoute
  '/_dashboard/prompts/': typeof DashboardPromptsIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/crm/users/$userId': typeof DashboardCrmUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/error'
    | '/agents'
    | '/crm'
    | '/journeys'
    | '/mindstate'
    | '/prompts'
    | '/settings'
    | '/users'
    | '/users-test'
    | '/'
    | '/agents/$agentKey'
    | '/developers/events'
    | '/journeys/$journeySlug'
    | '/mindstate/$definitionKey'
    | '/prompts/$promptName'
    | '/prompts/new'
    | '/settings/appearance'
    | '/settings/channels'
    | '/settings/import-export'
    | '/settings/journey-mindstate'
    | '/settings/journey-pipelines'
    | '/settings/organisation'
    | '/settings/profile'
    | '/settings/tags'
    | '/settings/variables'
    | '/agents/'
    | '/crm/'
    | '/journeys/'
    | '/mindstate/'
    | '/prompts/'
    | '/settings/'
    | '/crm/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/error'
    | '/users'
    | '/users-test'
    | '/'
    | '/agents/$agentKey'
    | '/developers/events'
    | '/journeys/$journeySlug'
    | '/mindstate/$definitionKey'
    | '/prompts/$promptName'
    | '/prompts/new'
    | '/settings/appearance'
    | '/settings/channels'
    | '/settings/import-export'
    | '/settings/journey-mindstate'
    | '/settings/journey-pipelines'
    | '/settings/organisation'
    | '/settings/profile'
    | '/settings/tags'
    | '/settings/variables'
    | '/agents'
    | '/crm'
    | '/journeys'
    | '/mindstate'
    | '/prompts'
    | '/settings'
    | '/crm/users/$userId'
  id:
    | '__root__'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/_dashboard'
    | '/error'
    | '/_dashboard/agents'
    | '/_dashboard/crm'
    | '/_dashboard/journeys'
    | '/_dashboard/mindstate'
    | '/_dashboard/prompts'
    | '/_dashboard/settings'
    | '/_dashboard/users'
    | '/_dashboard/users-test'
    | '/_dashboard/'
    | '/_dashboard/agents/$agentKey'
    | '/_dashboard/developers/events'
    | '/_dashboard/journeys/$journeySlug'
    | '/_dashboard/mindstate/$definitionKey'
    | '/_dashboard/prompts/$promptName'
    | '/_dashboard/prompts/new'
    | '/_dashboard/settings/appearance'
    | '/_dashboard/settings/channels'
    | '/_dashboard/settings/import-export'
    | '/_dashboard/settings/journey-mindstate'
    | '/_dashboard/settings/journey-pipelines'
    | '/_dashboard/settings/organisation'
    | '/_dashboard/settings/profile'
    | '/_dashboard/settings/tags'
    | '/_dashboard/settings/variables'
    | '/_dashboard/agents/'
    | '/_dashboard/crm/'
    | '/_dashboard/journeys/'
    | '/_dashboard/mindstate/'
    | '/_dashboard/prompts/'
    | '/_dashboard/settings/'
    | '/_dashboard/crm/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R401Route: typeof R401Route
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  R503Route: typeof R503Route
  DashboardRoute: typeof DashboardRouteWithChildren
  ErrorRoute: typeof ErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/503': {
      id: '/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof R503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users-test': {
      id: '/_dashboard/users-test'
      path: '/users-test'
      fullPath: '/users-test'
      preLoaderRoute: typeof DashboardUsersTestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/prompts': {
      id: '/_dashboard/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof DashboardPromptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/mindstate': {
      id: '/_dashboard/mindstate'
      path: '/mindstate'
      fullPath: '/mindstate'
      preLoaderRoute: typeof DashboardMindstateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/journeys': {
      id: '/_dashboard/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof DashboardJourneysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/crm': {
      id: '/_dashboard/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof DashboardCrmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents': {
      id: '/_dashboard/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/prompts/': {
      id: '/_dashboard/prompts/'
      path: '/'
      fullPath: '/prompts/'
      preLoaderRoute: typeof DashboardPromptsIndexRouteImport
      parentRoute: typeof DashboardPromptsRoute
    }
    '/_dashboard/mindstate/': {
      id: '/_dashboard/mindstate/'
      path: '/'
      fullPath: '/mindstate/'
      preLoaderRoute: typeof DashboardMindstateIndexRouteImport
      parentRoute: typeof DashboardMindstateRoute
    }
    '/_dashboard/journeys/': {
      id: '/_dashboard/journeys/'
      path: '/'
      fullPath: '/journeys/'
      preLoaderRoute: typeof DashboardJourneysIndexRouteImport
      parentRoute: typeof DashboardJourneysRoute
    }
    '/_dashboard/crm/': {
      id: '/_dashboard/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof DashboardCrmIndexRouteImport
      parentRoute: typeof DashboardCrmRoute
    }
    '/_dashboard/agents/': {
      id: '/_dashboard/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/_dashboard/settings/variables': {
      id: '/_dashboard/settings/variables'
      path: '/variables'
      fullPath: '/settings/variables'
      preLoaderRoute: typeof DashboardSettingsVariablesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/tags': {
      id: '/_dashboard/settings/tags'
      path: '/tags'
      fullPath: '/settings/tags'
      preLoaderRoute: typeof DashboardSettingsTagsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/profile': {
      id: '/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/organisation': {
      id: '/_dashboard/settings/organisation'
      path: '/organisation'
      fullPath: '/settings/organisation'
      preLoaderRoute: typeof DashboardSettingsOrganisationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/journey-pipelines': {
      id: '/_dashboard/settings/journey-pipelines'
      path: '/journey-pipelines'
      fullPath: '/settings/journey-pipelines'
      preLoaderRoute: typeof DashboardSettingsJourneyPipelinesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/journey-mindstate': {
      id: '/_dashboard/settings/journey-mindstate'
      path: '/journey-mindstate'
      fullPath: '/settings/journey-mindstate'
      preLoaderRoute: typeof DashboardSettingsJourneyMindstateRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/import-export': {
      id: '/_dashboard/settings/import-export'
      path: '/import-export'
      fullPath: '/settings/import-export'
      preLoaderRoute: typeof DashboardSettingsImportExportRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/channels': {
      id: '/_dashboard/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof DashboardSettingsChannelsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/appearance': {
      id: '/_dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/prompts/new': {
      id: '/_dashboard/prompts/new'
      path: '/new'
      fullPath: '/prompts/new'
      preLoaderRoute: typeof DashboardPromptsNewRouteImport
      parentRoute: typeof DashboardPromptsRoute
    }
    '/_dashboard/prompts/$promptName': {
      id: '/_dashboard/prompts/$promptName'
      path: '/$promptName'
      fullPath: '/prompts/$promptName'
      preLoaderRoute: typeof DashboardPromptsPromptNameRouteImport
      parentRoute: typeof DashboardPromptsRoute
    }
    '/_dashboard/mindstate/$definitionKey': {
      id: '/_dashboard/mindstate/$definitionKey'
      path: '/$definitionKey'
      fullPath: '/mindstate/$definitionKey'
      preLoaderRoute: typeof DashboardMindstateDefinitionKeyRouteImport
      parentRoute: typeof DashboardMindstateRoute
    }
    '/_dashboard/journeys/$journeySlug': {
      id: '/_dashboard/journeys/$journeySlug'
      path: '/$journeySlug'
      fullPath: '/journeys/$journeySlug'
      preLoaderRoute: typeof DashboardJourneysJourneySlugRouteImport
      parentRoute: typeof DashboardJourneysRoute
    }
    '/_dashboard/developers/events': {
      id: '/_dashboard/developers/events'
      path: '/developers/events'
      fullPath: '/developers/events'
      preLoaderRoute: typeof DashboardDevelopersEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/$agentKey': {
      id: '/_dashboard/agents/$agentKey'
      path: '/$agentKey'
      fullPath: '/agents/$agentKey'
      preLoaderRoute: typeof DashboardAgentsAgentKeyRouteImport
      parentRoute: typeof DashboardAgentsRoute
    }
    '/_dashboard/crm/users/$userId': {
      id: '/_dashboard/crm/users/$userId'
      path: '/users/$userId'
      fullPath: '/crm/users/$userId'
      preLoaderRoute: typeof DashboardCrmUsersUserIdRouteImport
      parentRoute: typeof DashboardCrmRoute
    }
  }
}

interface DashboardAgentsRouteChildren {
  DashboardAgentsAgentKeyRoute: typeof DashboardAgentsAgentKeyRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
}

const DashboardAgentsRouteChildren: DashboardAgentsRouteChildren = {
  DashboardAgentsAgentKeyRoute: DashboardAgentsAgentKeyRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
}

const DashboardAgentsRouteWithChildren = DashboardAgentsRoute._addFileChildren(
  DashboardAgentsRouteChildren,
)

interface DashboardCrmRouteChildren {
  DashboardCrmIndexRoute: typeof DashboardCrmIndexRoute
  DashboardCrmUsersUserIdRoute: typeof DashboardCrmUsersUserIdRoute
}

const DashboardCrmRouteChildren: DashboardCrmRouteChildren = {
  DashboardCrmIndexRoute: DashboardCrmIndexRoute,
  DashboardCrmUsersUserIdRoute: DashboardCrmUsersUserIdRoute,
}

const DashboardCrmRouteWithChildren = DashboardCrmRoute._addFileChildren(
  DashboardCrmRouteChildren,
)

interface DashboardJourneysRouteChildren {
  DashboardJourneysJourneySlugRoute: typeof DashboardJourneysJourneySlugRoute
  DashboardJourneysIndexRoute: typeof DashboardJourneysIndexRoute
}

const DashboardJourneysRouteChildren: DashboardJourneysRouteChildren = {
  DashboardJourneysJourneySlugRoute: DashboardJourneysJourneySlugRoute,
  DashboardJourneysIndexRoute: DashboardJourneysIndexRoute,
}

const DashboardJourneysRouteWithChildren =
  DashboardJourneysRoute._addFileChildren(DashboardJourneysRouteChildren)

interface DashboardMindstateRouteChildren {
  DashboardMindstateDefinitionKeyRoute: typeof DashboardMindstateDefinitionKeyRoute
  DashboardMindstateIndexRoute: typeof DashboardMindstateIndexRoute
}

const DashboardMindstateRouteChildren: DashboardMindstateRouteChildren = {
  DashboardMindstateDefinitionKeyRoute: DashboardMindstateDefinitionKeyRoute,
  DashboardMindstateIndexRoute: DashboardMindstateIndexRoute,
}

const DashboardMindstateRouteWithChildren =
  DashboardMindstateRoute._addFileChildren(DashboardMindstateRouteChildren)

interface DashboardPromptsRouteChildren {
  DashboardPromptsPromptNameRoute: typeof DashboardPromptsPromptNameRoute
  DashboardPromptsNewRoute: typeof DashboardPromptsNewRoute
  DashboardPromptsIndexRoute: typeof DashboardPromptsIndexRoute
}

const DashboardPromptsRouteChildren: DashboardPromptsRouteChildren = {
  DashboardPromptsPromptNameRoute: DashboardPromptsPromptNameRoute,
  DashboardPromptsNewRoute: DashboardPromptsNewRoute,
  DashboardPromptsIndexRoute: DashboardPromptsIndexRoute,
}

const DashboardPromptsRouteWithChildren =
  DashboardPromptsRoute._addFileChildren(DashboardPromptsRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsChannelsRoute: typeof DashboardSettingsChannelsRoute
  DashboardSettingsImportExportRoute: typeof DashboardSettingsImportExportRoute
  DashboardSettingsJourneyMindstateRoute: typeof DashboardSettingsJourneyMindstateRoute
  DashboardSettingsJourneyPipelinesRoute: typeof DashboardSettingsJourneyPipelinesRoute
  DashboardSettingsOrganisationRoute: typeof DashboardSettingsOrganisationRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsTagsRoute: typeof DashboardSettingsTagsRoute
  DashboardSettingsVariablesRoute: typeof DashboardSettingsVariablesRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
  DashboardSettingsChannelsRoute: DashboardSettingsChannelsRoute,
  DashboardSettingsImportExportRoute: DashboardSettingsImportExportRoute,
  DashboardSettingsJourneyMindstateRoute:
    DashboardSettingsJourneyMindstateRoute,
  DashboardSettingsJourneyPipelinesRoute:
    DashboardSettingsJourneyPipelinesRoute,
  DashboardSettingsOrganisationRoute: DashboardSettingsOrganisationRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardSettingsTagsRoute: DashboardSettingsTagsRoute,
  DashboardSettingsVariablesRoute: DashboardSettingsVariablesRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRouteWithChildren
  DashboardCrmRoute: typeof DashboardCrmRouteWithChildren
  DashboardJourneysRoute: typeof DashboardJourneysRouteWithChildren
  DashboardMindstateRoute: typeof DashboardMindstateRouteWithChildren
  DashboardPromptsRoute: typeof DashboardPromptsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardUsersTestRoute: typeof DashboardUsersTestRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDevelopersEventsRoute: typeof DashboardDevelopersEventsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRouteWithChildren,
  DashboardCrmRoute: DashboardCrmRouteWithChildren,
  DashboardJourneysRoute: DashboardJourneysRouteWithChildren,
  DashboardMindstateRoute: DashboardMindstateRouteWithChildren,
  DashboardPromptsRoute: DashboardPromptsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardUsersTestRoute: DashboardUsersTestRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDevelopersEventsRoute: DashboardDevelopersEventsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  R401Route: R401Route,
  R403Route: R403Route,
  R404Route: R404Route,
  R503Route: R503Route,
  DashboardRoute: DashboardRouteWithChildren,
  ErrorRoute: ErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
