/**
 * Notification Policies
 *
 * Centralized configuration that controls when events trigger user-facing toast notifications.
 * Events are ALWAYS emitted to SSE for logging and debugging - this file only controls which
 * events result in user notifications.
 *
 * This system enables context-aware notifications: the same event can trigger a notification
 * when initiated by an admin but remain silent when auto-generated by the engine.
 *
 * @module lib/events/notification-policies
 */

import type { EventType } from "@journey/schemas";
import type { FrontendEvent } from "./types";

/**
 * Notification Policy Type
 *
 * - "always": Always show a notification for this event
 * - "never": Never show a notification for this event (even if notify: true in registry)
 * - "conditional": Show notification based on event context (e.g., only if admin-initiated)
 */
export type NotificationPolicy =
  | { type: "always" }
  | { type: "never" }
  | { type: "conditional"; condition: (event: FrontendEvent) => boolean };

/**
 * Notification Policy Registry
 *
 * Maps event types to their notification policies.
 * Event types use dot notation (e.g., "tag.definition.created") as defined in EventTypes.
 * If an event type is not listed, the registry's notify config is used as fallback.
 */
export const NOTIFICATION_POLICIES: Partial<Record<EventType, NotificationPolicy>> = {
  // =========================================================================
  // TAG EVENTS
  // =========================================================================

  /**
   * "tag.definition.created"
   * Shows notification ONLY when admin manually creates a tag in Settings UI.
   * Suppresses notification when engine auto-creates tags during journey execution.
   *
   * performedBy values:
   * - "admin" → Manual creation from Settings
   * - "system" → Auto-creation from engine or org setup
   * - undefined → System operation
   */
  "tag.definition.created": {
    type: "conditional",
    condition: (event: FrontendEvent) => {
      const performedBy = event.performedBy;
      // Only notify for manual/admin operations, not system/engine auto-creation
      return performedBy !== "system" && performedBy !== undefined;
    },
  } as NotificationPolicy,

  /**
   * "tag.definition.deleted"
   * Always notify - tag deletion is always an explicit admin action.
   */
  "tag.definition.deleted": {
    type: "always",
  } as NotificationPolicy,

  // "tag.added" and "tag.removed" already have notify: false in event registry
  // so they don't need a policy here (registry config takes precedence)

  // =========================================================================
  // MINDSTATE EVENTS
  // =========================================================================

  /**
   * "mindstate.definition.created"
   * Shows notification only for manual creation, not during org initialization.
   * Suppresses notification when created as "system" operation.
   */
  "mindstate.definition.created": {
    type: "conditional",
    condition: (event: FrontendEvent) => event.performedBy !== "system",
  } as NotificationPolicy,

  /**
   * "mindstate.definition.deleted"
   * Always notify - deletion is always an explicit admin action.
   */
  "mindstate.definition.deleted": {
    type: "always",
  } as NotificationPolicy,

  // =========================================================================
  // CRM PIPELINE EVENTS
  // =========================================================================

  /**
   * "crm.pipeline.entered"
   * Never notify - clients are automatically assigned to pipelines on their first interaction.
   * This is expected/automatic behavior, not worth notifying admins about.
   * The actual pipeline and stage updates are what matter, not client entry.
   */
  "crm.pipeline.entered": {
    type: "never",
  } as NotificationPolicy,

  /**
   * "crm.pipeline.created"
   * Always notify - creating pipelines is always an explicit admin action.
   */
  "crm.pipeline.created": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "crm.pipeline.exited"
   * Never notify - client exit is automatic and less important than entry.
   */
  "crm.pipeline.exited": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // CRM STAGE EVENTS
  // =========================================================================

  /**
   * "crm.stage.created"
   * Always notify - creating new pipeline stages is an explicit admin action.
   */
  "crm.stage.created": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "crm.stage.deleted"
   * Always notify - deleting stages is an important admin action.
   */
  "crm.stage.deleted": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "crm.stage.changed"
   * Never notify - stage changes are frequent (kanban drag-drop) and have visual feedback.
   * The kanban board already shows the change visually, no need for a toast.
   */
  "crm.stage.changed": {
    type: "never",
  } as NotificationPolicy,

  /**
   * "crm.stages.reordered"
   * Never notify - stage reordering is a UI operation with immediate visual feedback.
   */
  "crm.stages.reordered": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // BOT EVENTS
  // =========================================================================

  /**
   * "bot.created"
   * Always notify - new bot registration is an important admin action.
   */
  "bot.created": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "bot.deleted"
   * Always notify - bot deletion is an important action.
   */
  "bot.deleted": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "bot.activated"
   * Always notify - activating a bot is important (goes live).
   */
  "bot.activated": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "bot.deactivated"
   * Always notify - deactivating a bot is important (takes offline).
   */
  "bot.deactivated": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "bot.webhook.registered"
   * Never notify - webhook registration is a technical detail.
   */
  "bot.webhook.registered": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // JOURNEY EVENTS
  // =========================================================================

  /**
   * "journey.created"
   * Always notify - new journey creation is an important admin action.
   */
  "journey.created": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "journey.deleted"
   * Always notify - journey deletion is an important action.
   */
  "journey.deleted": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "journey.activated"
   * Always notify - activating a journey means it goes live. Critical to know.
   */
  "journey.activated": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "journey.deactivated"
   * Always notify - deactivating a journey is important. Stops interactions.
   */
  "journey.deactivated": {
    type: "always",
  } as NotificationPolicy,

  /**
   * "journey.updated"
   * Never notify - updates are frequent and have auto-save with indicator.
   * The save manager handles update notifications separately.
   */
  "journey.updated": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // JOURNEY SESSION & RUNTIME EVENTS
  // =========================================================================
  // These are all engine/runtime events that shouldn't notify users

  /**
   * "journey.session.started", "journey.session.completed", etc.
   * Never notify - these are runtime events, not admin actions.
   * Event logs track these, but users don't need notifications.
   */
  "journey.session.started": {
    type: "never",
  } as NotificationPolicy,

  "journey.session.completed": {
    type: "never",
  } as NotificationPolicy,

  "journey.schedule.fired": {
    type: "never",
  } as NotificationPolicy,

  "journey.webhook.received": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // CRM FIELD & MESSAGE EVENTS
  // =========================================================================

  /**
   * "crm.field.updated"
   * Never notify - field updates are frequent background operations.
   */
  "crm.field.updated": {
    type: "never",
  } as NotificationPolicy,

  /**
   * "crm.message.sent"
   * Never notify - message sending is tracked in event log, doesn't need toast.
   */
  "crm.message.sent": {
    type: "never",
  } as NotificationPolicy,

  /**
   * "crm.action.executed", "crm.action.failed"
   * Never notify - action feedback is handled separately in the UI.
   */
  "crm.action.executed": {
    type: "never",
  } as NotificationPolicy,

  "crm.action.failed": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // USER INTERACTION EVENTS
  // =========================================================================
  // These are runtime events that don't warrant admin notifications

  /**
   * "user.message", "user.click", "engine.message", "engine.transition", etc.
   * Never notify - these are high-volume runtime events.
   * They're logged for analytics, but shouldn't spam notifications.
   */
  "user.message": {
    type: "never",
  } as NotificationPolicy,

  "user.click": {
    type: "never",
  } as NotificationPolicy,

  "engine.message": {
    type: "never",
  } as NotificationPolicy,

  "engine.transition": {
    type: "never",
  } as NotificationPolicy,

  "engine.error": {
    type: "never",
  } as NotificationPolicy,

  "timer.expired": {
    type: "never",
  } as NotificationPolicy,

  "timer.followup": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // SESSION & WORKFLOW EVENTS
  // =========================================================================

  /**
   * "session.tags", "session.variables"
   * Never notify - tag/variable changes during sessions are high-volume.
   */
  "session.tags": {
    type: "never",
  } as NotificationPolicy,

  "session.variables": {
    type: "never",
  } as NotificationPolicy,

  "variable.changed": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // WORKFLOW EVENTS
  // =========================================================================
  // Workflow execution events shouldn't notify - they're internal

  "workflow.started": {
    type: "never",
  } as NotificationPolicy,

  "workflow.completed": {
    type: "never",
  } as NotificationPolicy,

  "workflow.error": {
    type: "never",
  } as NotificationPolicy,

  "workflow.step.started": {
    type: "never",
  } as NotificationPolicy,

  "workflow.step.completed": {
    type: "never",
  } as NotificationPolicy,

  "workflow.step.error": {
    type: "never",
  } as NotificationPolicy,

  "workflow.paused": {
    type: "never",
  } as NotificationPolicy,

  "workflow.resumed": {
    type: "never",
  } as NotificationPolicy,

  "workflow.approval.requested": {
    type: "never",
  } as NotificationPolicy,

  "workflow.approval.response": {
    type: "never",
  } as NotificationPolicy,

  "workflow.guard.blocked": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // LLM & MINDSTATE EVENTS
  // =========================================================================

  /**
   * "llm.hitl", "llm.guard.blocked", "llm.guard.fallback"
   * Never notify - these are handled separately in the UI or event logs.
   */
  "llm.hitl": {
    type: "never",
  } as NotificationPolicy,

  "llm.guard.blocked": {
    type: "never",
  } as NotificationPolicy,

  "llm.guard.fallback": {
    type: "never",
  } as NotificationPolicy,

  "mindstate.updated": {
    type: "never",
  } as NotificationPolicy,

  // =========================================================================
  // JOURNEY ENGINE EVENTS
  // =========================================================================

  /**
   * "journey.teleport", "journey.crm"
   * Never notify - these are internal engine operations.
   */
  "journey.teleport": {
    type: "never",
  } as NotificationPolicy,

  "journey.crm": {
    type: "never",
  } as NotificationPolicy,
};

/**
 * Evaluate whether an event should trigger a user-facing notification
 *
 * @param event - The frontend event to evaluate
 * @returns true if a notification should be shown, false otherwise
 */
export function shouldNotify(event: FrontendEvent): boolean {
  const policy = NOTIFICATION_POLICIES[event.type as EventType];

  // If no policy is defined for this event type, allow the notification
  // (fallback to the registry's notify config)
  if (!policy) {
    return true;
  }

  switch (policy.type) {
    case "always":
      return true;

    case "never":
      return false;

    case "conditional":
      return policy.condition(event);
  }
}
